AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template creates an AWS IAM Role with an inline policy and two AWS managed policies
  attached. It sets the trust policy on that IAM Role to permit a named ARN in another AWS
  account to assume that role. The role name and the ARN of the trusted user can all be passed
  to the CloudFormation stack as parameters.
Parameters:
  AuthorizedARN:
    Description: "ARN of IAM Role which is authorized to assume the ProwlerExecRole role."
    Type: String

  ProwlerExecRoleName:
    Description: "Name of the IAM role that will have these policies attached. Default: ProwlerExecRole"
    Type: String
    Default: "ProwlerExecRole"

Resources:
  ProwlerExecRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "The resource must remain as * in order to assess all IAM Users."
          - id: W28
            reason: "The IAM Role name is specified as an explicit for use within the scripting"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub ${AuthorizedARN}
            Action: "sts:AssumeRole"
      MaxSessionDuration: 43200
      ManagedPolicyArns:  #SecurityAudit and ViewOnly Access are used as per Prowler requirements to grant the appropriate level of read-only access to resources
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/SecurityAudit"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess"
      RoleName: !Sub ${ProwlerExecRoleName}
      Policies:
        - PolicyName: ProwlerExecRoleAdditionalViewPrivileges
          PolicyDocument:
            Version: "2012-10-17"
            Statement:  #Actions below are given against all resources as per Prowler requirements to grant the appropriate level of read-only access to resources
              - Effect: Allow
                Action:
                  - account:Get*,
                  - appstream:Describe*,
                  - appstream:List*,
                  - backup:List*,
                  - cloudtrail:GetInsightSelectors,
                  - codeartifact:List*,
                  - codebuild:BatchGet*,
                  - dlm:Get*,
                  - drs:Describe*,
                  - ds:Get*,
                  - ds:Describe*,
                  - ds:List*,
                  - ec2:GetEbsEncryptionByDefault,
                  - ecr:Describe*,
                  - ecr:GetRegistryScanningConfiguration,
                  - elasticfilesystem:DescribeBackupPolicy,
                  - glue:GetConnections,
                  - glue:GetSecurityConfiguration*,
                  - glue:SearchTables,
                  - lambda:GetFunction*,
                  - logs:FilterLogEvents,
                  - macie2:GetMacieSession,
                  - s3:GetAccountPublicAccessBlock,
                  - shield:DescribeProtection,
                  - shield:GetSubscriptionState,
                  - securityhub:BatchImportFindings,
                  - securityhub:GetFindings,
                  - ssm:GetDocument,
                  - ssm-incidents:List*,
                  - support:Describe*,
                  - tag:GetTagKeys,
                  - wellarchitected:List*
                  - organizations:DescribeOrganization
                  - organizations:ListPolicies*
                  - organizations:DescribePolicy
                  - organizations:ListDelegatedAdministrators
                Resource: "*"
              - Effect: Allow
                Action:
                  - apigateway:GET
                Resource:
                  - !Sub "arn:${AWS::Partition}:apigateway:*::/restapis/*"
                  - !Sub "arn:${AWS::Partition}:apigateway:*::/apis/*"
